# https://github.com/marketplace/actions/deploy-to-heroku
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12

        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "rt-chat-backend" #Must be unique in Heroku
          heroku_email: "rogeriobrum@gmail.com"
          usedocker: true
          docker_build_args: |
            NODE_ENV
            PORT
            JWT_SECRET
            FRONTEND_URL
            MONGO_URI
        env:
          NODE_ENV: "production"
          PORT: "443"
          JWT_SECRET: "${{secrets.JWT_SECRET}}"
          FRONTEND_URL: "https://chat-frontend.rogeriobrum.com"
          MONGO_URI: "${{secrets.MONGO_URI}}"